- hosts: "{{hosts}}"
  gather_facts: false
  remote_user: "{{user}}"
  vars:
    - deploy_file:  /var/lib/jenkins/workspace/springboot_tomcat/target/hello-springboot-1.3.5.RELEASE.war
    - service_name:  demo
    - deploy_path: "~/app/{{service_name}}"
    - jar_name: "{{service_name}}"
    - service_port: 8000
    - start_cmd:  "nohup java  -jar  11272050_hello-springboot-1.3.5.RELEASE.war >> demo.log&"
  roles:
    - spring
